home/urls.py
from django.urls import path
from .views import home, model_predict, get_predict_result, upload_model


urlpatterns = [
    path("", home, name="home"),
    path("model/predict/<int:id>", model_predict, name="model_predict"),
    path("model/predict/result/<int:id>", get_predict_result, name="get_predict_result"),
    path("model/upload", upload_model, name="model_upload")
    # path('register/', register_user, name="register"),
    # path("logout/", LogoutView.as_view(), name="logout")
]
app_name = "home"

imd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("auth/", include("authentication.urls")),
    path("train/", include("train.urls")),
    # path("", include("home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.
# ML model store model
# name: name of the model
# description: description of the model
# model: the model file
# created_at: the time when the model is created
# updated_at: the time when the model is updated
# accuracy: the accuracy of the model

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class MLModel(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000, default="", null=True, blank=True)
    model_file = models.FileField(upload_to=user_directory_path, null=True, blank=True)
    accuracy = models.FloatField(default=0.0)
    output = models.CharField(max_length=100, default="", null=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class MLModelInput(models.Model):
    INPUT_TYPE_CHOICES = (
        ('text', 'str'),
        ('checkbox', 'checkbox'),
        ('number', 'float'),
        ('number', 'int'),
        ('file', 'file'),
        ('image', 'image'),
    )
    name = models.CharField(max_length=100)
    attribute = models.CharField(max_length=100, default='', null=True, blank=True)
    description = models.CharField(max_length=1000, null=True, blank=True)
    input_type = models.CharField(max_length=100, choices=INPUT_TYPE_CHOICES, default='float')
    model = models.ForeignKey(MLModel, on_delete=models.CASCADE, related_name='inputs')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


# ML model input store model
# name: name of the model input
# attribute: the attribute of the input
# description: description of the model input
# input_type: the type of the input
# model: the model that the input belongs to
# created_at: the time when the model input is created
# updated_at: the time when the model input is updated        

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# import login required decorator
from django.contrib.auth.decorators import login_required
from .models import MLModel, MLModelInput
from django.views.decorators.csrf import csrf_exempt
import pickle
import sklearn
import json

# Create your views here.
@login_required(login_url="/auth/login/")
def home(request):
    # get all the models
    ml_models = MLModel.objects.filter(user=request.user)
    context = {
        "ml_models": ml_models
    }
    return render(request, "home/index.html", {"data": context})


def model_predict(request, id):
    # print("model_id", id)
    # get the model
    ml_model = MLModel.objects.get(id=id)
    # get the model inputs
    ml_model_inputs = ml_model.inputs.all()
    context = {
        "ml_model": ml_model,
        "ml_model_inputs": ml_model_inputs
    }
    # print("context", context)
    return render(request, "home/predict.html", {"data": context})

@csrf_exempt
def get_predict_result(request, id):
    if request.method == "POST":
        data = json.loads(request.body.decode('utf-8'))
        input_data_str = data.get('inputValues')
        print("input_data_str", input_data_str)
        input_data = [float(x) for x in input_data_str] 
        print("input_data", input_data)
        # print("model_id", id)
        # get the model
        ml_model = MLModel.objects.get(id=id)

        # pickle the model
        model_file = ml_model.model_file
        pickled_model = pickle.load(open(model_file.path, 'rb'))
        

        ml_result = pickled_model.predict([input_data])
        print("ml_result", ml_result)
        print("type(ml_result[0])", type(ml_result[0]))
        
        data = {
            "result": ml_result[0],
            "message": "Predict result successfuly!"
            }
        if type(ml_result[0]) != int:
            # print("here")
            ml_result = str(ml_result[0])
            # print("ml_result", ml_result)
            data = {
                "result": ml_result,
            }
        # data = {'message': 'Hello, world!'}
        json_content = json.dumps(data)
        return HttpResponse(json_content, content_type='application/json; charset=utf-8')  
    
def upload_model(request):
    if request.method == "POST":
        print("request.POST", request.POST.dict())
        print("request.FILES", request.FILES)
        model_file = request.FILES.get('model_file')
        # print(model_file)
        data_dict = request.POST.dict()
        data_dict.pop('csrfmiddlewaretoken')
        ml_model = MLModel(
            name=data_dict.get('model_name'),
            description=data_dict.get('model_desc'),
            model_file=model_file,
            accuracy=data_dict.get('accuracy'),
            output=data_dict.get('model_output_name'),
            user=request.user,
        )
        ml_model.save()
        # get the model inputs
        for i in range(1, int(data_dict.get('input_count'))+1):
            ml_model_input = MLModelInput(
                name=data_dict.get('input-name-'+str(i)),
                input_type=data_dict.get('input-type-'+str(i)),
                model=ml_model
            )
            ml_model_input.save()

        
    return render(request, "home/upload_model.html")

templates/home/login.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Login {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary border-0 mb-0">
            <div class="card-header bg-transparent pb-5">
              <div class="text-muted text-center mt-2 mb-3"><small>Sign in with</small></div>
              <div class="btn-wrapper text-center">
                <a href="#" class="btn btn-neutral btn-icon">
                  <span class="btn-inner--icon"><img src="/static/assets/img/icons/common/github.svg"></span>
                  <span class="btn-inner--text">Github</span>
                </a>
                <a href="#" class="btn btn-neutral btn-icon">
                  <span class="btn-inner--icon"><img src="/static/assets/img/icons/common/google.svg"></span>
                  <span class="btn-inner--text">Google</span>
                </a>
              </div>
            </div>
            <div class="card-body px-lg-5 py-lg-5">
              <div class="text-center text-muted mb-4">
                <small>Or sign in with credentials</small>
              </div>
              <form role="form" action="/">
                <div class="form-group mb-3">
                  <div class="input-group input-group-merge input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                    </div>
                    <input class="form-control" placeholder="Email" type="email">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-merge input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                    </div>
                    <input class="form-control" placeholder="Password" type="password">
                  </div>
                </div>
                <div class="custom-control custom-control-alternative custom-checkbox">
                  <input class="custom-control-input" id=" customCheckLogin" type="checkbox">
                  <label class="custom-control-label" for=" customCheckLogin">
                    <span class="text-muted">Remember me</span>
                  </label>
                </div>
                <div class="text-center">
                  <button type="button" class="btn btn-primary my-4">Sign in</button>
                </div>
              </form>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/register.html" class="text-light"><small>Create Account</small></a>
            </div>
            {% comment %} <div class="col-6 text-right">
              <a href="https://appseed.us?ref=j2-argon-demo" class="text-light"><small>Get Support</small></a>
            </div> {% endcomment %}
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/home/map.html
{% extends 'layouts/base.html' %}

{% block title %} Maps {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Google maps</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Maps</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Google maps</li>
                </ol>
              </nav>
            </div>
            <div class="col-lg-6 col-5 text-right">
              <a href="#" class="btn btn-sm btn-neutral">New</a>
              <a href="#" class="btn btn-sm btn-neutral">Filters</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--6">
      <div class="row">
        <div class="col">
          <div class="card border-0">
            <div id="map-default" class="map-canvas" data-lat="40.748817" data-lng="-73.985428" style="height: 600px;"></div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}
      
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

{% endblock javascripts %}

templates/home/page-403.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 403      
              </div>

              <div class="text-center mb-4">
                Access denied - Please authenticate <a href="{% url 'login' %}">Login</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>          
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/home/page-404.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 404      
              </div>

              <div class="text-center mb-4">
                Page not found - <a href="/">Home</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/home/page-500.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 500      
              </div>

              <div class="text-center mb-4">
                Server error, please contact support - <a href="/">Home</a>.
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
              <a target="_blank" 
                 href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/home/register.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Register {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <!-- Page content -->
  <div class="container mt--8 pb-5">
    <!-- Table -->
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card bg-secondary border-0">
          <div class="card-header bg-transparent pb-5">
            <div class="text-muted text-center mt-2 mb-4"><small>Sign up with</small></div>
            <div class="text-center">
              <a href="#" class="btn btn-neutral btn-icon mr-4">
                <span class="btn-inner--icon"><img src="/static/assets/img/icons/common/github.svg"></span>
                <span class="btn-inner--text">Github</span>
              </a>
              <a href="#" class="btn btn-neutral btn-icon">
                <span class="btn-inner--icon"><img src="/static/assets/img/icons/common/google.svg"></span>
                <span class="btn-inner--text">Google</span>
              </a>
            </div>
          </div>
          <div class="card-body px-lg-5 py-lg-5">
            <div class="text-center text-muted mb-4">
              <small>Or sign up with credentials</small>
            </div>
            <form role="form">
              <div class="form-group">
                <div class="input-group input-group-merge input-group-alternative mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                  </div>
                  <input class="form-control" placeholder="Name" type="text">
                </div>
              </div>
              <div class="form-group">
                <div class="input-group input-group-merge input-group-alternative mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                  </div>
                  <input class="form-control" placeholder="Email" type="email">
                </div>
              </div>
              <div class="form-group">
                <div class="input-group input-group-merge input-group-alternative">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                  </div>
                  <input class="form-control" placeholder="Password" type="password">
                </div>
              </div>
              <div class="text-muted font-italic"><small>password strength: <span class="text-success font-weight-700">strong</span></small></div>
              <div class="row my-4">
                <div class="col-12">
                  <div class="custom-control custom-control-alternative custom-checkbox">
                    <input class="custom-control-input" id="customCheckRegister" type="checkbox">
                    <label class="custom-control-label" for="customCheckRegister">
                      <span class="text-muted">I agree with the <a href="#!">Privacy Policy</a></span>
                    </label>
                  </div>
                </div>
              </div>
              <div class="text-center">
                <button type="button" class="btn btn-primary mt-4">Create account</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/home/upload_model.html
{% extends 'layouts/base.html' %} {% block title %} Profile {% endblock title %}
{% block content %}

<!-- Page content -->
<div class="container-fluid mt-4">
  <div class="row">
    <!-- <div class="col-xl-4 order-xl-2">
      <div class="card card-profile">
        <img src="/static/assets/img/theme/img-1-1000x600.jpg" alt="Image placeholder" class="card-img-top">
        <div class="row justify-content-center">
          <div class="col-lg-3 order-lg-2">
            <div class="card-profile-image">
              <a href="#">
                <img src="/static/assets/img/theme/team-4.jpg" class="rounded-circle">
              </a>
            </div>
          </div>
        </div>
        <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
          <div class="d-flex justify-content-between">
            <a href="#" class="btn btn-sm btn-info  mr-4 ">Connect</a>
            <a href="#" class="btn btn-sm btn-default float-right">Message</a>
          </div>
        </div>
        <div class="card-body pt-0">
          <div class="row">
            <div class="col">
              <div class="card-profile-stats d-flex justify-content-center">
                <div>
                  <span class="heading">22</span>
                  <span class="description">Friends</span>
                </div>
                <div>
                  <span class="heading">10</span>
                  <span class="description">Photos</span>
                </div>
                <div>
                  <span class="heading">89</span>
                  <span class="description">Comments</span>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center">
            <h5 class="h3">
              {{ request.user.username }}
            </h5>
            <div class="h5 font-weight-300">
              {{ request.user.email }}
            </div>
            <div class="h5 mt-4">
              <i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer
            </div>
            <div>
              <i class="ni education_hat mr-2"></i>University of Computer Science
            </div>
          </div>
        </div>
      </div>
    </div> -->
    <div class="col-xl-8 order-xl-1">
      <div class="card">
        <!-- <div class="card-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h3 class="mb-0">Edit profile </h3>
            </div>
            <div class="col-4 text-right">
              <a href="#!" class="btn btn-sm btn-primary">Settings</a>
            </div>
          </div>
        </div> -->
        <div class="card-body">
          <form method="post" action="{% url 'home:model_upload' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <h6 class="heading-title text-body mb-4">
              Instant Model Deployment
            </h6>
            <hr class="my-4" />
            <div class="pl-lg-4">
              <div class="column" style="margin-bottom: 30px">
                <label for="model_file" style="margin-right: 20px"
                  >Upload your ML Model:
                </label>
                <input type="file" id="model_file" name="model_file" />
              </div>
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-username"
                      >Model Name</label
                    >
                    <input
                      type=""
                      id="input-username"
                      class="form-control"
                      placeholder="Enter model name"
                      value=""
                      name="model_name"
                    />
                  </div>
                </div>

                <div class="col-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-accuracy"
                      >Accuracy</label
                    >
                    <input
                      type="number"
                      id="input-accuracy"
                      class="form-control"
                      placeholder="Enter accuracy"
                      name="accuracy"
                      step="0.01"
                    />
                  </div>
                </div>

                <div class="col-lg-12">
                  <div class="form-group">
                    <label class="form-control-label" for="input-desc"
                      >Description</label
                    >
                    <input
                      type="text"
                      id="input-desc"
                      class="form-control"
                      placeholder="Write your model description here"
                      name="model_desc"
                      step="0.01"
                    />
                  </div>
                </div>

                <div class="col-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-numbers"
                      >No. of inputs</label
                    >
                    <input
                      type="number"
                      id="input-numbers"
                      class="form-control"
                      placeholder="Number of X attributes"
                      name="input_count"
                    />
                  </div>
                </div>
                <div class="col-lg-6" style="align-self: center">
                  <button type="button" class="btn btn-sm btn-primary" onclick="generateInputs()">
                    Generate
                  </button>
                </div>

                <div id="final-generated-inputs">
                  <!-- <div class="row generated-inputs">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-username"
                          >Name of 1st Input :</label
                        >
                        <input
                          type=""
                          id="input-username"
                          class="form-control"
                          placeholder=""
                          value=""
                        />
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-username"
                          >Type of 1st input :</label
                        >
                        <select name="pets" id="pet-select">
                          <option value="">--Please choose an option--</option>
                          <option value="number">Integer</option>
                          <option value="number">Float</option>
                          <option value="file">File</option>
                          <option value="image">Image</option>
                        </select>
                      </div>
                    </div>
                  </div> -->
                </div>
              </div>
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label class="form-control-label" for="input-username"
                      >Output Name</label
                    >
                    <input
                      type="text"
                      id="input-output-name"
                      class="form-control"
                      placeholder="Enter output name"
                      value=""
                      name="model_output_name"
                    />
                  </div>
                </div>
              </div>
            </div>
            <hr class="my-4" />
            <button type="submit" class="btn btn-lg btn-primary">
              Upload ML Model
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>

  {% include "includes/footer.html" %}
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script>
  window.onload = function () {
    // Scroll down by 20 pixels
    window.scrollBy(0, 200);
  };
</script>
<script>
  let generateInputs = function(){
    console.log("clickedd")
    const generatedInputDiv = document.getElementsByClassName("generated-inputs")
    console.log(generatedInputDiv) 
    let inputNumbers = document.getElementById("input-numbers").value
    console.log(inputNumbers)

    
    let finalGenInputs = ``;              
    for (let i=1; i<=inputNumbers; i++){
      let inputStr = `<div class="row generated-inputs">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-name"
                          >Name of Input ${i}:</label
                        >
                        <input
                          type="text"
                          id="input-name-${i}"
                          class="form-control"
                          placeholder=""
                          value=""
                          name="input-name-${i}"
                        />
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-type"
                          >Type of input ${i}:</label
                        >
                        <select name="input-type-${i}" id="inputs-select-${i}">
                          <option value="">--Please choose an option--</option>
                          <option value="number">Integer</option>
                          <option value="number">Float</option>
                          <option value="text">String</option>
                          <option value="file">File</option>
                          <option value="image">Image</option>
                        </select>
                      </div>
                    </div>
                  </div>`;
          finalGenInputs += inputStr;        
    }
    let finalGenInputsDiv = document.getElementById("final-generated-inputs")
    finalGenInputsDiv.innerHTML = finalGenInputs;
  }
</script>
{% endblock javascripts %}