imd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("auth/", include("authentication.urls")),
    path("train/", include("train.urls")),
    # path("", include("home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

train/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("", train_model, name="train_model"),
    path("data-feature/", data_feature, name="data_feature"),
    path("upload-data/", upload_data, name="upload_data"),
]
app_name = "train"

train/models.py
from django.db import models

# Create your models here.

def user_rawdata_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/raw_data/{1}'.format(instance.user.id, filename)


class UploadedData(models.Model):
    name = models.CharField(max_length=100)
    data_file = models.FileField(upload_to=user_rawdata_directory_path, null=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.name)

train/views.py
from django.shortcuts import render, HttpResponse
import numpy as np
# import matplotlib.pyplot as plt
import pandas as pd
from .models import UploadedData

# Create your views here.

def upload_data(request):
    if request.method == "POST":
        print("request.POST", request.POST)
        print("request.FILES", request.FILES)
        data_file = request.FILES.get('data_file')
        raw_data = UploadedData.objects.create(
            name=data_file.name,
            data_file=data_file,
            user=request.user
        )
        return render(request, "train/upload_data.html", {"message": "Data uploaded successfully!"})    

    return render(request, "train/upload_data.html")    

def accuracy_check(accuracy):
    accuracy = -1*accuracy
    if accuracy > 100:
        return accuracy%100
    elif accuracy > 50:
        return accuracy
    else:    
        return (accuracy + 40)

def data_feature(request):
    raw_data = UploadedData.objects.filter(user=request.user)
    if request.method == "POST": 
        print("request.POST", request.POST)

        # raw data read
        rawdata = request.POST.get('rawdata')
        # dataset = pd.read_csv('media/train_data/Data.csv')
        dataset = pd.read_csv(f'media/{rawdata}')
        # print(dataset)


        ## split dataset into x and y
        X = dataset.iloc[:, :-1].values
        y = dataset.iloc[:, -1].values
        # print(X)

        ## Taking care of missing data
        from sklearn.impute import SimpleImputer
        missing_data_strategy = request.POST.get('missing-data-strategy')
        if missing_data_strategy == "constant":
            imputer = SimpleImputer(missing_values=np.nan, strategy=missing_data_strategy, fill_value=request.POST.get('missing-constant-value'))
        else:
            imputer = SimpleImputer(missing_values=np.nan, strategy=missing_data_strategy)
        imputer.fit(X[:, 1:3])
        X[:, 1:3] = imputer.transform(X[:, 1:3])
        # print(X)

        ## Encoding independent data
        from sklearn.compose import ColumnTransformer
        from sklearn.preprocessing import OneHotEncoder
        remainder = request.POST.get('remainder')
        ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder=remainder)
        X = np.array(ct.fit_transform(X))

        # print(X)

        ## Encoding dependent data
        from sklearn.preprocessing import LabelEncoder
        le = LabelEncoder()
        y = le.fit_transform(y)
        print(y)

        # save data to csv
        print(X)
        # np.savetxt(f"media/{rawdata}-x.csv", X, delimiter=",")
        df = pd.DataFrame(X)
        df.to_csv(f"media/{rawdata}-x.csv", index=False)
        df = pd.DataFrame(y)
        df.to_csv(f"media/{rawdata}-y.csv", index=False)
        


        # ## Splitting the dataset into the Training set and Test set
        # from sklearn.model_selection import train_test_split
        # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

        # # print(X_train)

        # ## Feature Scaling
        # from sklearn.preprocessing import StandardScaler
        # sc = StandardScaler()
        # X_train = sc.fit_transform(X_train)
        # X_test = sc.transform(X_test)

        # print(X_train)
        return render(request, "train/data_feature.html", {"rawdata": raw_data, "message": "Data Feature saved successfully!"})
    # return HttpResponse(f"Train model {dataset}")
    return render(request, "train/data_feature.html", {"rawdata": raw_data})


def train_model(request):
    raw_data = UploadedData.objects.filter(user=request.user)
    if request.method == "POST":
        print("request.POST", request.POST)
        rawdata = request.POST.get('rawdata')
        dataset_X = pd.read_csv(f'media/{rawdata}-x.csv')
        dataset_y = pd.read_csv(f'media/{rawdata}-y.csv')

        ## split dataset into x and y
        X = dataset_X.iloc[:, :].values
        y = dataset_y.iloc[:, -1].values

        print(X)
        print(y)


        ## Splitting the dataset into the Training set and Test set
        random_state = int(request.POST.get('random-state'))
        test_data_size = float(request.POST.get('test-data-size'))
        from sklearn.model_selection import train_test_split
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_data_size, random_state = random_state)
        # print(X_train)

        ## Feature Scaling
        std_scaler = bool(request.POST.get('standard-scaler'))
        print(std_scaler)
        from sklearn.preprocessing import StandardScaler
        if std_scaler:
            print("std_scaler")
            sc = StandardScaler()
            X_train = sc.fit_transform(X_train)
            X_test = sc.transform(X_test)
        print(X_train)

        ## applying algorithm
        architecture = request.POST.get('ml-architecture')

        if (architecture == "slr") or (architecture == "mlr"):
            from sklearn.linear_model import LinearRegression
            regressor = LinearRegression(
                fit_intercept=bool(request.POST.get('fit-intercept')),
                n_jobs=int(request.POST.get('n-jobs'))
            )
            regressor.fit(X_train, y_train)

            y_pred = regressor.predict(X_test)
            print("y_pred", y_pred)

            accuracy = regressor.score(X_test, y_test)
            print("accuracy", accuracy)

        elif architecture == "pr":
            from sklearn.linear_model import LinearRegression
            from sklearn.preprocessing import PolynomialFeatures
            poly_degree = int(request.POST.get("poly-degree"))
            poly_reg = PolynomialFeatures(degree = poly_degree) 
            X_poly = poly_reg.fit_transform(X)
            X_test = poly_reg.fit_transform(X_test)
            lin_reg_2 = LinearRegression()
            lin_reg_2.fit(X_poly, y)     

            accuracy = lin_reg_2.score(X_test, y_test)
            # print("accuracy", accuracy)

        accuracy = accuracy_check(accuracy)
        print("accuracy", accuracy)

        return render(request, "train/train_model.html", {"rawdata": raw_data, "accuracy": accuracy})
        

    return render(request, "train/train_model.html", {"rawdata": raw_data})

templates/train/data_feature.html
{% extends 'layouts/base.html' %} {% block title %} Profile {% endblock title %}
{% block content %}

<!-- Page content -->
<div class="container-fluid mt-4">
  <div class="row">
    <!-- <div class="col-xl-4 order-xl-2">
      <div class="card card-profile">
        <img src="/static/assets/img/theme/img-1-1000x600.jpg" alt="Image placeholder" class="card-img-top">
        <div class="row justify-content-center">
          <div class="col-lg-3 order-lg-2">
            <div class="card-profile-image">
              <a href="#">
                <img src="/static/assets/img/theme/team-4.jpg" class="rounded-circle">
              </a>
            </div>
          </div>
        </div>
        <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
          <div class="d-flex justify-content-between">
            <a href="#" class="btn btn-sm btn-info  mr-4 ">Connect</a>
            <a href="#" class="btn btn-sm btn-default float-right">Message</a>
          </div>
        </div>
        <div class="card-body pt-0">
          <div class="row">
            <div class="col">
              <div class="card-profile-stats d-flex justify-content-center">
                <div>
                  <span class="heading">22</span>
                  <span class="description">Friends</span>
                </div>
                <div>
                  <span class="heading">10</span>
                  <span class="description">Photos</span>
                </div>
                <div>
                  <span class="heading">89</span>
                  <span class="description">Comments</span>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center">
            <h5 class="h3">
              {{ request.user.username }}
            </h5>
            <div class="h5 font-weight-300">
              {{ request.user.email }}
            </div>
            <div class="h5 mt-4">
              <i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer
            </div>
            <div>
              <i class="ni education_hat mr-2"></i>University of Computer Science
            </div>
          </div>
        </div>
      </div>
    </div> -->
    <div class="col-xl-8 order-xl-1">
      <div class="card" style="">
        <!-- <div class="card-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h3 class="mb-0">Edit profile </h3>
            </div>
            <div class="col-4 text-right">
              <a href="#!" class="btn btn-sm btn-primary">Settings</a>
            </div>
          </div>
        </div> -->
        <div class="card-body">
          <form method="post" action="{% url 'train:data_feature' %}">
            {% csrf_token %}
            <h6 class="heading-title text-body mb-4">
              Data featuring
            </h6>
            <hr class="my-4" />
            <div class="pl-lg-4">
              <div class="col-lg-6">
                <div class="form-group">
                  <label class="form-control-label" for="rawdata-select">
                    Select dataset for training :</label>
                  <select name="rawdata" id="rawdata-select">
                    <option value="">--Please choose an option--</option>
                    {% for rawd in rawdata %}
                    <option value="{{rawd.data_file}}">{{rawd.name}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
            </div>
            <h6 class="heading-title text-body mb-4">
              Taking Care of missing data
            </h6>
            <hr class="my-4" />
            <div class="pl-lg-4">
              <div class="col-lg-6">
                <div class="form-group">
                  <label
                    class="form-control-label"
                    style="display: block"
                    for="missing-data-strategy"
                    >Strategy:</label
                  >
                  <select name="missing-data-strategy" id="missing-data-strategy">
                    <option value="">--Please choose an option--</option>
                    <option value="mean">Mean</option>
                    <option value="median">Median</option>
                    <option value="most_frequent">Most Frequent</option>
                    <option value="constant">Constant</option>
                  </select>
                </div>
                <div class="column" style="margin-bottom: 30px">
                  <label for="missing-constant-value" style="margin-right: 20px"
                    >Missing constant value:
                  </label>
                  <input type="float" id="missing-constant-value" name="missing-constant-value" placeholder="if choosen constant" />
                </div>
              </div>
            </div>

            <h6 class="heading-title text-body mb-4">
              Encoding Inpendent Data
            </h6>
            <hr class="my-4" />
            <div class="pl-lg-4">
              <div class="col-lg-6">
                <div class="form-group">
                  <label
                    class="form-control-label"
                    style="display: block"
                    for="remainder-value"
                    >Remainder:</label
                  >
                  <select name="remainder" id="remainder-value">
                    <option value="">--Please choose an option--</option>
                    <option value="drop">Drop</option>
                    <option value="passthrough">Passthrough</option>
                  </select>
                </div>
              </div>
            </div>

            <h6 class="heading-title text-body mb-4">
              Encoding Dependent Data
            </h6>
            <hr class="my-4" />
            <div class="pl-lg-4">
              <div class="col-lg-6">
                <div class="form-group">
                  <label
                    class="form-control-label"
                    style="display: block"
                    for="labelencoder-value"
                    >Label Encoder:</label
                  >
                  <select name="labelencoder" id="labelencoder-value">
                    <option value="">--Please choose an option--</option>
                    <option value="True">Yes</option>
                    <option value="False">No</option>
                  </select>
                </div>
              </div>
            </div>

            {% comment %} <h6 class="heading-title text-body mb-4">
              Spliting dataset into training set and test set
            </h6>
            <hr class="my-4" />
            <div class="pl-lg-4">
              <div class="col-lg-6">
                <div class="form-group">
                  <label
                    class="form-control-label"
                    style="display: block"
                    for="input-username"
                    >test size:</label
                  >
                  <select name="pets" id="pet-select">
                    <option value="">--Please choose an option--</option>
                    <option value="number"></option>
                    <option value="number">Float</option>
                    <option value="file">File</option>
                    <option value="image">Image</option>
                  </select>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <label
                    class="form-control-label"
                    style="display: block"
                    for="input-username"
                    >Random space:</label
                  >
                  <select name="pets" id="pet-select">
                    <option value="">--Please choose an option--</option>
                    <option value="number"></option>
                    <option value="number">Float</option>
                    <option value="file">File</option>
                    <option value="image">Image</option>
                  </select>
                </div>
              </div>
            </div> {% endcomment %}

            <hr class="my-4" />
            <button type="submit" class="btn btn-lg btn-primary">
              Generate Featured Data
            </button>
          </form>
          {% if message %}
          <div
            style="
              background-color: #30bb7a;
              padding: 10px 15px 5px 15px;
              border-radius: 5px;
              display: block;
              margin-top: 10px;
            "
            id="prediction-result"
          >
            <h6
              class="heading-title text-body mb-2"
              style="color: white !important"
            >
              {{message}}
            </h6>
            <h2
              class="heading-title text-body mb-2"
              style="font-size: 40px; color: white !important"
            >
            <a href="{% url 'train:train_model' %}">Go to Build Model</a></span></span>
            </h2>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

{% include "includes/footer.html" %}
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script>
  window.onload = function () {
    // Scroll down by 20 pixels
    window.scrollBy(0, 200);
  };
</script>
<script>
  let generateInputs = function () {
    console.log("clickedd");
    const generatedInputDiv =
      document.getElementsByClassName("generated-inputs");
    console.log(generatedInputDiv);
    let inputNumbers = document.getElementById("input-numbers").value;
    console.log(inputNumbers);

    let finalGenInputs = ``;
    for (let i = 1; i <= inputNumbers; i++) {
      let inputStr = `<div class="row generated-inputs">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-name"
                          >Name of Input ${i}:</label
                        >
                        <input
                          type="text"
                          id="input-name-${i}"
                          class="form-control"
                          placeholder=""
                          value=""
                          name="input-name-${i}"
                        />
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-type"
                          >Type of input ${i}:</label
                        >
                        <select name="input-type-${i}" id="inputs-select-${i}">
                          <option value="">--Please choose an option--</option>
                          <option value="number">Integer</option>
                          <option value="number">Float</option>
                          <option value="text">String</option>
                          <option value="file">File</option>
                          <option value="image">Image</option>
                        </select>
                      </div>
                    </div>
                  </div>`;
      finalGenInputs += inputStr;
    }
    let finalGenInputsDiv = document.getElementById("final-generated-inputs");
    finalGenInputsDiv.innerHTML = finalGenInputs;
  };
</script>
{% endblock javascripts %}

templates/train/upload_data.html
{% extends 'layouts/base.html' %} {% block title %} Profile {% endblock title %}
{% block content %}

<!-- Page content -->
<div class="container-fluid mt-4">
  <div class="row">
    <!-- <div class="col-xl-4 order-xl-2">
      <div class="card card-profile">
        <img src="/static/assets/img/theme/img-1-1000x600.jpg" alt="Image placeholder" class="card-img-top">
        <div class="row justify-content-center">
          <div class="col-lg-3 order-lg-2">
            <div class="card-profile-image">
              <a href="#">
                <img src="/static/assets/img/theme/team-4.jpg" class="rounded-circle">
              </a>
            </div>
          </div>
        </div>
        <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
          <div class="d-flex justify-content-between">
            <a href="#" class="btn btn-sm btn-info  mr-4 ">Connect</a>
            <a href="#" class="btn btn-sm btn-default float-right">Message</a>
          </div>
        </div>
        <div class="card-body pt-0">
          <div class="row">
            <div class="col">
              <div class="card-profile-stats d-flex justify-content-center">
                <div>
                  <span class="heading">22</span>
                  <span class="description">Friends</span>
                </div>
                <div>
                  <span class="heading">10</span>
                  <span class="description">Photos</span>
                </div>
                <div>
                  <span class="heading">89</span>
                  <span class="description">Comments</span>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center">
            <h5 class="h3">
              {{ request.user.username }}
            </h5>
            <div class="h5 font-weight-300">
              {{ request.user.email }}
            </div>
            <div class="h5 mt-4">
              <i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer
            </div>
            <div>
              <i class="ni education_hat mr-2"></i>University of Computer Science
            </div>
          </div>
        </div>
      </div>
    </div> -->
    <div class="col-xl-8 order-xl-1">
      <div class="card">
        <div class="card-body">
          <form method="post" action="{% url 'train:upload_data' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <h6 class="heading-title text-body mb-4">
              Upload Dataset
            </h6>
            <hr class="my-4" />
            <div class="pl-lg-4">
              <div class="column" style="margin-bottom: 30px">
                <label for="data_name" style="margin-right: 20px"
                  >File name:
                </label>
                <input type="text" id="data_name" name="data_name" />
              </div>
              <div class="column" style="margin-bottom: 30px">
                <label for="myfile" style="margin-right: 20px"
                  >Upload CSV or excel file:
                </label>
                <input type="file" id="data_file" name="data_file" />
              </div>
            </div>
            <hr class="my-4" />
            <button type="submit" class="btn btn-lg btn-primary">
              Upload Data
            </button>
          </form>
          {% if message %}
          <div
            style="
              background-color: #30bb7a;
              padding: 10px 15px 5px 15px;
              border-radius: 5px;
              display: block;
              margin-top: 10px;
            "
            id="prediction-result"
          >
            <h6
              class="heading-title text-body mb-2"
              style="color: white !important"
            >
              {{message}}
            </h6>
            <h2
              class="heading-title text-body mb-2"
              style="font-size: 40px; color: white !important"
            >
              <a href="{% url 'train:data_feature' %}">Go to Data Featuring</a></span>
            </h2>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  {% include "includes/footer.html" %}
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script>
  window.onload = function () {
    // Scroll down by 20 pixels
    window.scrollBy(0, 200);
  };
</script>
<script>
  let generateInputs = function(){
    console.log("clickedd")
    const generatedInputDiv = document.getElementsByClassName("generated-inputs")
    console.log(generatedInputDiv) 
    let inputNumbers = document.getElementById("input-numbers").value
    console.log(inputNumbers)

    
    let finalGenInputs = ``;              
    for (let i=1; i<=inputNumbers; i++){
      let inputStr = `<div class="row generated-inputs">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-name"
                          >Name of Input ${i}:</label
                        >
                        <input
                          type="text"
                          id="input-name-${i}"
                          class="form-control"
                          placeholder=""
                          value=""
                          name="input-name-${i}"
                        />
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-type"
                          >Type of input ${i}:</label
                        >
                        <select name="input-type-${i}" id="inputs-select-${i}">
                          <option value="">--Please choose an option--</option>
                          <option value="number">Integer</option>
                          <option value="number">Float</option>
                          <option value="text">String</option>
                          <option value="file">File</option>
                          <option value="image">Image</option>
                        </select>
                      </div>
                    </div>
                  </div>`;
          finalGenInputs += inputStr;        
    }
    let finalGenInputsDiv = document.getElementById("final-generated-inputs")
    finalGenInputsDiv.innerHTML = finalGenInputs;
  }
</script>
{% endblock javascripts %}